### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by aileoia** [Dreknor/MitarbeiterBoard#13]
Hello Dreknor,
thank you so much for the "MitarbeiterBoard".

I' trying to let it run on my machine and I have some troubles installing all the dependencies. Could you please indicate me all the steps or packages needed, when starting from a blank, freshly installed system, e.g. ubuntu?

Thank you so much in advance!

Léo

**Comment by Dreknor** [comment]
1. Setup Apache + PHP (version ^7.2.5) and mariadb (or mysql)
2. Setting up Composer
3. clone git repository to public webserver directory
4. use composer install in project dir

**Comment by aileoia** [comment]
Ich bin jetzt weiter gekommen und konnte erfolgreich "composer install" laufen lassen. (Es hatten mir einige php extensions gefehlt).

Jetzt scheitere ich an "php artisan migrate". Beim ersten mal bekomme ich folgende Fehlermeldung:

```
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table

   Illuminate\Database\QueryException 

  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null (SQL: insert into `users` (`name`, `email`, `password`, `created_at`, `updated_at`) values (MitarbeiterBoard, ?, $2y$10$9iNJe29CX1.luIwnlSU.herTej9xiA1dDxGm4O241hxRuBu7Kl4iW, 2021-03-14 15:23:09, 2021-03-14 15:23:09))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

      +7 vendor frames 
  8   database/migrations/2014_10_12_000000_create_users_table.php:31
      Illuminate\Database\Query\Builder::insert()

      +21 vendor frames 
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Wenn ich es nochmal laufen lasse bekomme ich
```
Migrating: 2014_10_12_000000_create_users_table

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

      +9 vendor frames 
  10  database/migrations/2014_10_12_000000_create_users_table.php:24
      Illuminate\Support\Facades\Facade::__callStatic("create")

      +21 vendor frames 
  32  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
Ich nehme an, ich habe die datenbank nicht richtig konfiguriert.
Hättest du eine schnelle Idee, was ich da machen kann?

Vielen Dank im Vorraus!
Léo

**Comment by Dreknor** [comment]
Zunächst:
php artisan migrate:rollback

Damit wird die bestehende Tablelle gelöscht.
Dann bitte kontrollieren, dass in der .env -Datei MAIL_FROM_NAME einen Namen beinhaltet und MAIL_FROM_ADDRESS eine gültige Mail-Adresse. 

Anschließend kann der Befehl 
php artisan migrate 
erneut durchgeführt werden.

**Comment by aileoia** [comment]
Großartig, das klingt gut!
ich probiere es mal.

**Comment by albig** [comment]
Hallo @Dreknor,

ich versuche auch gerade das MitarbeiterBoard zu installieren unter Debian 10.

1. Versuch mit `composer install` schlägt fehl:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jean85/pretty-package-versions 2.0.3 -> satisfiable by jean85/pretty-package-versions[2.0.3].
    - jean85/pretty-package-versions 2.0.3 requires composer-runtime-api ^2.0.0 -> no matching package found.
  Problem 2
    - Installation request for spatie/laravel-medialibrary 9.4.3 -> satisfiable by spatie/laravel-medialibrary[9.4.3].
    - spatie/laravel-medialibrary 9.4.3 requires php ^7.4|^8.0 -> your PHP version (7.3.27) does not satisfy that requirement.
  Problem 3
    - jean85/pretty-package-versions 2.0.3 requires composer-runtime-api ^2.0.0 -> no matching package found.
    - sentry/sentry 3.2.0 requires jean85/pretty-package-versions ^1.5|^2.0.1 -> satisfiable by jean85/pretty-package-versions[2.0.3].
    - Installation request for sentry/sentry 3.2.0 -> satisfiable by sentry/sentry[3.2.0].
```
--> also ist das Requirement Composer 2? Debian 10 bringt zunächst nur composer 1.8.4 mit.

2. Versuch mit composer 2.0 schlägt nun hier fehl:

```
    - spatie/laravel-medialibrary is locked to version 9.4.3 and an update of this package was not requested.
    - spatie/laravel-medialibrary 9.4.3 requires php ^7.4|^8.0 -> your php version (7.3.27) does not satisfy that requirement.
```

---> also ist das Requirement PHP ^7.4? Debian 10 bringt nur 7.3.27 out-of-the box mit.

```

**Comment by aileoia** [comment]
@albig ich war in der lage composer + artisan zum laufen zu bringen in einem docker container.  Die Mariadb kann man auch optimal in einem container laufen lassen und das alles mit docker-compose sehr angenehm und reprozierbar deploybar machen. Den dockerfile habe ich in meinem Fork eingecheckt https://github.com/aileoia/MitarbeiterBoard/blob/master/Dockerfile

Was mir noch fehlt ist die apache config im container, was für euch beide kein ding sein sollte, und dann der feinschliff.  Um das mit docker laufen zu lassen (zumindest bis dahin wo ich es selber geschaft habe) muss man:
```
# docker installieren
sudo apt install docker.io

# Image bauen
cd path/to/MitarbeiterBoard
docker build -t mibo .

# Docker networ erstellen um mit der db zu sprechen
docker network create db-net

# Mariadb starten
docker run --rm -ti -p 3306:3306 --name mariadb-server --net db-net -e MYSQL_ROOT_PASSWORD=1234 mariadb

# MiBo starten
docker run --rm -ti --net db-net -p 8080:80 -v $PWD/.env:/opt/app/.env -v $PWD/index.html:/var/www/html/index.html mibo /bin/bash
```
Mit dem letzten Kommando befindet sich man in dem container wo `compose` schon gelaufen ist und nur noch die `artisan` befehle fehlen.  In dem obigen kommando bedeuten
* `-p 8080:80` der port 8080 vom host wird auf den port 80 des containers geleitet, man kann also im container apache auf 80 konfigurieren
* `-v $PWD/.env:/opt/app/.env` die datei `.env` auf dem host soll im container unter `/opt/app/.env` zu sehen sein.  Man kann die Datei im host ändert und sieht es dann im container
* Das letzte `/bin/bash` heißt: "container laufen und kommando im container ausführen", deswegen landet man mit einer shell im container

Für die Mariadb genügt das offizielle image: https://hub.docker.com/_/mariadb

Ich würde noch eine docker compose datei schreiben, sodass man mit `docker-compose up` alles hoch startet und alle parameter oben sind in der datei persistent zu finden.

@albig ich mache sehr gerne eine kleine session mit dir, ich denke es lohnt sich wirklich, es bringt richtig viel im bereich reproduzierbarkeit, fähigkeit etwas zurückzurollen etc...

@Dreknor wenn das alles erfolgreich ist könnte man sich vorstellen ein docker image auf dockerhub hochzuladen, sodass weitere interessenten block ein `docker-compose up` machen müssen, und alles ist da...

**Comment by Dreknor** [comment]
Das könnt ihr sehr gern machen. Da wir einen Hoster nutzen, der Docker nicht unterstützt, habe ich da nie Energie rein gesteckt.

**Comment by aileoia** [comment]
@Dreknor ich war jetzt auch in der lage, das ganze zum laufen zu bringen.

Allerdings sehe ich dann wenig funktionalitäten, wahrscheinlich fehlt es bei mir an Konfiguration irgendwo. Ich sehe nur "Home" "Beratungen" und "Gruppen" und kann so gut wie nichts machen. Habe ich etwas in der Konfig verpasst?

**Comment by Dreknor** [comment]
Da sind die Rechte nicht korrekt gesetzt worden.
Bitte mal die geänderte Migration ziehen und dann per 
php artisan migrate:fresh
die Migration der Datenbank erneut durchführen.

**Comment by aileoia** [comment]
Ich verstehe.
Sinde es die rechte der dateien? Sind die rechte in der datenbank?
entschuldige mein unwissen...

**Comment by Dreknor** [comment]
Einfach nur die Rechte innerhalb der Anwendung. Das was du siehst ist überwiegend durch die verschiedenen Rechte und Rollen gesteuert. Der Admin sollte die wichtigsten Rechte direkt mit dem Start bekommen um dann selbst Rollen zu definieren und deren Rechte zu steuern. Am 31.03.2021 18:29 schrieb aileoia ***@***.***>:
Ich verstehe.
Sinde es die rechte der dateien? Sind die rechte in der datenbank?
entschuldige mein unwissen...
